# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed54998c07d38ce6c3939443dbe19f8409042ef4b473ef2906113a604dcb47364e92a5d4df763a410429a493cacc4c6bd031c41b4f2bcfa56ec63bc30ba7207d

test:
  secret_key_base: 390bebeb993cd54e1ab6207292b94f1d32ea274fc59485d1ccf98505e6973a16691d59cfbd2126f791fbfa84833947dba6617a4bddbcc1be4beec5c7423e1d95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
